-- MySQL Script generated by MySQL Workbench
-- mié 01 may 2019 23:52:35 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id9455940_bdqcinfo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id9455940_bdqcinfo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id9455940_bdqcinfo` DEFAULT CHARACTER SET utf8 ;
USE `id9455940_bdqcinfo` ;

-- -----------------------------------------------------
-- Table `id9455940_bdqcinfo`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id9455940_bdqcinfo`.`Usuarios` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id9455940_bdqcinfo`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id9455940_bdqcinfo`.`Reportes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Aula` VARCHAR(10) NOT NULL,
  `Hora` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  `Imagen` VARCHAR(45) NULL,
  `IdUsuarios` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Reportes_Usuarios_idx` (`IdUsuarios` ASC),
  CONSTRAINT `fk_Reportes_Usuarios`
    FOREIGN KEY (`IdUsuarios`)
    REFERENCES `id9455940_bdqcinfo`.`Usuarios` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id9455940_bdqcinfo`.`Avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id9455940_bdqcinfo`.`Avisos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Hora` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  `Contenido` VARCHAR(100) NOT NULL,
  `IdUsuarios` INT NOT NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Coord_Inco_Usuarios_idx` (`IdUsuarios` ASC),
  CONSTRAINT `fk_Avisos_Usuarios`
    FOREIGN KEY (`IdUsuarios`)
    REFERENCES `id9455940_bdqcinfo`.`Usuarios` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
